version: '3.8'

services:
  web:
    image: web:latest
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             gunicorn smart_home.wsgi -b 0.0.0.0:8000:application --workers 3 --timeout 60"
    env_file: ".env"
    depends_on:
      - db

  db:
    image: postgres
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/volumes/postgres:/var/lib/postgresql/data

  nginx:
    image: custom_nginx:latest
    ports:
      - "80:80"

networks:
  default:
    name: service_network
